---
- hosts: all
  sudo: true
  vars:
    app_root: /vagrant
    sys_packages: []
    php_packages: ["php5-cli","php5-xdebug"]
    php_ppa: php5-oldstable
    zsh_theme: af-magic
  roles:
    - init
    - oh-my-zsh
    - phpcommon
    - composer
