---
- name: "Setup postgres cluster to default to utf8 | stop cluster"
  sudo: yes
  sudo_user: postgres
  shell: pg_dropcluster --stop {{ pg_version }} {{ pg_cluster }}
  tags:
    - postgres

- name: "Setup postgres cluster to default to utf8 | start cluster"
  sudo: yes
  sudo_user: postgres
  shell: pg_createcluster --start -e {{ pg_encoding }} {{ pg_version }} {{ pg_cluster }}
  tags:
    - postgres
